### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by DarWcy** [ZPiDER666/vscjsontableeditor#1]
Hi There,

I've installed this extention in my VS Code, and created sample JSON file.
But how to open/trigger this extention?
I'm new to VS Code, hope you can help to point me out?

thanks.

**Comment by ZPiDER666** [comment]
Hi DarWcy, you will need a specific format of JSON file, for details please refer to the help of the extension on the VSCode marketplace. here is a very minimal example:

```
{
    "mode": "default",
    "schema": {
        "url": "String"
    },
    "rows": [
        {
            "url": "http://alturos.com"
        }
    ]
}
```

**Comment by ZPiDER666** [comment]
it will also work when you have a simpler file like this:

```
[
   { "url": "https://something.com" }
]
```

then it will automatically infer the schema.

i recommend calling your files *.tc.json - then the plugin will open the file by default when clicking on it in the navigator.
on a *.json file you may also rightclick and select Open With... and then select the JSON Table Editor.

**Comment by DarWcy** [comment]
Got it, thanks ZPiDER666.
