### ISSUE TITLE
After 100 records it is very slow

### ISSUE THREAD

**Issue by manuelmsu** [ZPiDER666/vscjsontableeditor#4]
Hi,

Very good app. The idea is wonderful, and it works with nested structures.

But beyond a small number of records (approximately 100) navigation is very, very slow.

Also, every time you commit a change, the focus always goes to the first line.

Thanks for your application.

**Comment by ZPiDER666** [comment]
@manuelmsu, thanks for the feedback, i will have a look at the many-items-problem

**Comment by ZPiDER666** [comment]
@manuelmsu, i agree, it gets quite sluggish to use in my test with 150 items. also i can reproduce your focus/scrolling problem. i'll try to come up with a fix.

**Comment by ZPiDER666** [comment]
after many experiments and research i found a few approaches to fixing this problem:
- virtual scrolling: only render the lines that are actually visible. this is basically working, but the whole scrolling mechanic, size  calculations, etc. have to change, so this will take me at least another week to fully implement and test
- grid rendering: even with virtual scrolling we need to render 50 lines on large screens which is still slow for some cases. i have read, that using other elements than tables, vue.js performance can greatly improve, however this will likely mean i have to do many sizing calculations on my own where i initially relied on tables.

btw i have found and fixed the weird focussing behaviour you are describing, but this fix will only come out together with the changes above.

so i am asking for a bit of patience.

**Comment by ZPiDER666** [comment]
finally managed to get everything working again.
behaviour of the table had to change significantly, now all columns have a fixed width and scrolling is virtual.

check out v0.10.0

it should be pretty quick to work with larger datasets now, but it is still no big-data-tool :)
i hope you all like the changes!

**Comment by ZPiDER666** [comment]
closing issue

**Comment by manuelmsu** [comment]
Thank you very much for everything!

Exceptional! It’s the most amazing thing I’ve seen for working with JSON. Congratulations on your great work!

If it seems good to you, I’ll open another task for you to evaluate the possibility of exporting to Excel.

**Comment by ZPiDER666** [comment]
thanks for the feedback!
